
package com.grpname.budgetbitesmain;

public class ForgotPassword extends javax.swing.JFrame {

    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newPw1 = new javax.swing.JLabel();
        mailField1 = new javax.swing.JTextField();
        confirmPw1 = new javax.swing.JLabel();
        confirmBtn1 = new javax.swing.JButton();
        clearBtn1 = new javax.swing.JButton();
        userMail1 = new javax.swing.JLabel();
        oldPw1 = new javax.swing.JLabel();
        newPwField1 = new javax.swing.JPasswordField();
        confirmPwField1 = new javax.swing.JPasswordField();
        oldPwField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(199, 201, 120));

        jPanel1.setBackground(new java.awt.Color(199, 201, 120));

        newPw1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        newPw1.setForeground(new java.awt.Color(90, 0, 0));
        newPw1.setText("New Password:");

        mailField1.setForeground(new java.awt.Color(102, 102, 102));
        mailField1.setText("johndoe@gmail.com");
        mailField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mailField1MouseClicked(evt);
            }
        });

        confirmPw1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        confirmPw1.setForeground(new java.awt.Color(90, 0, 0));
        confirmPw1.setText("Confirm Password:");

        confirmBtn1.setBackground(new java.awt.Color(0, 0, 0));
        confirmBtn1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        confirmBtn1.setForeground(new java.awt.Color(255, 255, 255));
        confirmBtn1.setText("CONFIRM");

        clearBtn1.setBackground(new java.awt.Color(0, 0, 0));
        clearBtn1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        clearBtn1.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn1.setText("CLEAR");
        clearBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearBtn1MouseClicked(evt);
            }
        });
        clearBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn1ActionPerformed(evt);
            }
        });

        userMail1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        userMail1.setForeground(new java.awt.Color(90, 0, 0));
        userMail1.setText("Your Email:");

        oldPw1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        oldPw1.setForeground(new java.awt.Color(90, 0, 0));
        oldPw1.setText("Old Password:");

        newPwField1.setForeground(new java.awt.Color(102, 102, 102));
        newPwField1.setText("jPasswordField1");
        newPwField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newPwField1MouseClicked(evt);
            }
        });
        newPwField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPwField1ActionPerformed(evt);
            }
        });

        confirmPwField1.setForeground(new java.awt.Color(102, 102, 102));
        confirmPwField1.setText("jPasswordField2");
        confirmPwField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmPwField1MouseClicked(evt);
            }
        });

        oldPwField1.setForeground(new java.awt.Color(102, 102, 102));
        oldPwField1.setText("jPasswordField3");
        oldPwField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oldPwField1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(oldPw1)
                    .addComponent(userMail1)
                    .addComponent(newPw1)
                    .addComponent(confirmPw1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mailField1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldPwField1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPwField1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(confirmBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(confirmPwField1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userMail1)
                    .addComponent(mailField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPw1)
                    .addComponent(oldPwField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(newPw1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(newPwField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(confirmPw1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(confirmPwField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void clearBtn1MouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void clearBtn1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        mailField1.setText("");
        oldPwField1.setText("");
        confirmPwField1.setText("");
        newPwField1.setText("");
    }                                         

    private void newPwField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void oldPwField1MouseClicked(java.awt.event.MouseEvent evt) {                                         
        oldPwField1.setText("");
    }                                        

    private void newPwField1MouseClicked(java.awt.event.MouseEvent evt) {                                         
        newPwField1.setText("");
    }                                        

    private void confirmPwField1MouseClicked(java.awt.event.MouseEvent evt) {                                             
        confirmPwField1.setText("");
    }                                            

    private void mailField1MouseClicked(java.awt.event.MouseEvent evt) {                                        
        mailField1.setText("");
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton clearBtn1;
    private javax.swing.JButton confirmBtn1;
    private javax.swing.JLabel confirmPw1;
    private javax.swing.JPasswordField confirmPwField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mailField1;
    private javax.swing.JLabel newPw1;
    private javax.swing.JPasswordField newPwField1;
    private javax.swing.JLabel oldPw1;
    private javax.swing.JPasswordField oldPwField1;
    private javax.swing.JLabel userMail1;
    // End of variables declaration                   
}

